// sources.js — Catalogue complet des sources de veille
// Format : { id, name, url, feedUrl, category, subCategory, language, active }
// feedUrl = URL du flux RSS/Atom (null = scraping non supporté sur GitHub Pages)

const CATEGORIES = {
  ANDROID: 'Android',
  IOS: 'iOS',
  QA: 'QA / QC Mobile',
  AI_TESTING: 'IA & Automatisation',
  PRIVACY: 'Privacy & Légal',
};

const SOURCES = [
  // ── ANDROID — Sources officielles ─────────────────────────────────────────
  {
    id: 'android-dev-blog',
    name: 'Android Developers Blog',
    url: 'https://android-developers.googleblog.com/',
    feedUrl: 'https://feeds.feedburner.com/blogspot/hsDu',
    category: CATEGORIES.ANDROID,
    subCategory: 'Officiel',
    language: 'en',
    active: true,
  },
  {
    id: 'google-android-blog',
    name: 'Google Android Blog',
    url: 'https://blog.google/products/android/',
    feedUrl: 'https://blog.google/rss/',
    category: CATEGORIES.ANDROID,
    subCategory: 'Officiel',
    language: 'en',
    active: true,
  },
  {
    id: 'pixel-bulletins',
    name: 'Pixel Update Bulletins',
    url: 'https://source.android.com/docs/security/bulletin/pixel',
    feedUrl: 'https://source.android.com/feeds/pixel-bulletins.atom',
    category: CATEGORIES.ANDROID,
    subCategory: 'Officiel',
    language: 'en',
    active: true,
  },

  // ── ANDROID — Médias anglophones ───────────────────────────────────────────
  {
    id: '9to5google',
    name: '9to5Google',
    url: 'https://9to5google.com/',
    feedUrl: 'https://9to5google.com/feed/',
    category: CATEGORIES.ANDROID,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },
  {
    id: 'android-police',
    name: 'Android Police',
    url: 'https://www.androidpolice.com/',
    feedUrl: 'https://www.androidpolice.com/feed/',
    category: CATEGORIES.ANDROID,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },
  {
    id: 'android-authority',
    name: 'Android Authority',
    url: 'https://www.androidauthority.com/',
    feedUrl: 'https://www.androidauthority.com/feed/',
    category: CATEGORIES.ANDROID,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },
  {
    id: 'android-central',
    name: 'Android Central',
    url: 'https://www.androidcentral.com/',
    feedUrl: 'https://www.androidcentral.com/rss.xml',
    category: CATEGORIES.ANDROID,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },
  {
    id: 'xda-developers',
    name: 'XDA Developers',
    url: 'https://www.xda-developers.com/',
    feedUrl: 'https://www.xda-developers.com/feed/',
    category: CATEGORIES.ANDROID,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },
  {
    id: 'ars-technica-gadgets',
    name: 'Ars Technica — Gadgets',
    url: 'https://arstechnica.com/gadgets/',
    feedUrl: 'https://feeds.arstechnica.com/arstechnica/gadgets',
    category: CATEGORIES.ANDROID,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },

  // ── ANDROID — Médias francophones ─────────────────────────────────────────
  {
    id: 'frandroid',
    name: 'FrAndroid',
    url: 'https://www.frandroid.com/',
    feedUrl: 'https://www.frandroid.com/feed',
    category: CATEGORIES.ANDROID,
    subCategory: 'Média FR',
    language: 'fr',
    active: true,
  },
  {
    id: 'phonandroid',
    name: 'Phonandroid',
    url: 'https://www.phonandroid.com/',
    feedUrl: 'https://www.phonandroid.com/feed',
    category: CATEGORIES.ANDROID,
    subCategory: 'Média FR',
    language: 'fr',
    active: true,
  },
  {
    id: 'journal-du-geek',
    name: 'Journal du Geek',
    url: 'https://www.journaldugeek.com/',
    feedUrl: 'https://www.journaldugeek.com/feed/',
    category: CATEGORIES.ANDROID,
    subCategory: 'Média FR',
    language: 'fr',
    active: true,
  },

  // ── iOS — Sources officielles ──────────────────────────────────────────────
  {
    id: 'apple-newsroom',
    name: 'Apple Newsroom',
    url: 'https://www.apple.com/newsroom/',
    feedUrl: 'https://www.apple.com/newsroom/rss-feed.rss',
    category: CATEGORIES.IOS,
    subCategory: 'Officiel',
    language: 'en',
    active: true,
  },
  {
    id: 'apple-developer-news',
    name: 'Apple Developer News',
    url: 'https://developer.apple.com/news/',
    feedUrl: 'https://developer.apple.com/news/rss/news.rss',
    category: CATEGORIES.IOS,
    subCategory: 'Officiel',
    language: 'en',
    active: true,
  },

  // ── iOS — Médias anglophones ───────────────────────────────────────────────
  {
    id: '9to5mac',
    name: '9to5Mac',
    url: 'https://9to5mac.com/',
    feedUrl: 'https://9to5mac.com/feed/',
    category: CATEGORIES.IOS,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },
  {
    id: 'macrumors',
    name: 'MacRumors',
    url: 'https://www.macrumors.com/',
    feedUrl: 'https://feeds.macrumors.com/MacRumors-All',
    category: CATEGORIES.IOS,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },
  {
    id: 'appleinsider',
    name: 'AppleInsider',
    url: 'https://appleinsider.com/',
    feedUrl: 'https://appleinsider.com/rss/news/',
    category: CATEGORIES.IOS,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },
  {
    id: 'imore',
    name: 'iMore',
    url: 'https://www.imore.com/',
    feedUrl: 'https://www.imore.com/rss.xml',
    category: CATEGORIES.IOS,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },
  {
    id: 'six-colors',
    name: 'Six Colors',
    url: 'https://sixcolors.com/',
    feedUrl: 'https://sixcolors.com/feed.json',
    category: CATEGORIES.IOS,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },
  {
    id: 'daring-fireball',
    name: 'Daring Fireball',
    url: 'https://daringfireball.net/',
    feedUrl: 'https://daringfireball.net/feeds/main',
    category: CATEGORIES.IOS,
    subCategory: 'Média EN',
    language: 'en',
    active: true,
  },

  // ── iOS — Médias francophones ──────────────────────────────────────────────
  {
    id: 'igen',
    name: 'iGeneration',
    url: 'https://www.igen.fr/',
    feedUrl: 'https://www.igen.fr/rss.xml',
    category: CATEGORIES.IOS,
    subCategory: 'Média FR',
    language: 'fr',
    active: true,
  },
  {
    id: 'macgeneration',
    name: 'MacGeneration',
    url: 'https://www.macg.co/',
    feedUrl: 'https://www.macg.co/rss.xml',
    category: CATEGORIES.IOS,
    subCategory: 'Média FR',
    language: 'fr',
    active: true,
  },
  {
    id: 'consomac',
    name: 'Consomac',
    url: 'https://consomac.fr/',
    feedUrl: 'https://consomac.fr/news.xml',
    category: CATEGORIES.IOS,
    subCategory: 'Média FR',
    language: 'fr',
    active: true,
  },

  // ── QA / QC MOBILE ────────────────────────────────────────────────────────
  {
    id: 'ministry-of-testing',
    name: 'Ministry of Testing',
    url: 'https://www.ministryoftesting.com/',
    feedUrl: 'https://www.ministryoftesting.com/feed',
    category: CATEGORIES.QA,
    subCategory: 'Communauté',
    language: 'en',
    active: true,
  },
  {
    id: 'test-guild',
    name: 'Test Guild',
    url: 'https://testguild.com/',
    feedUrl: 'https://testguild.com/feed/',
    category: CATEGORIES.QA,
    subCategory: 'Blog',
    language: 'en',
    active: true,
  },
  {
    id: 'software-testing-news',
    name: 'Software Testing News',
    url: 'https://www.softwaretestingnews.co.uk/',
    feedUrl: 'https://www.softwaretestingnews.co.uk/feed/',
    category: CATEGORIES.QA,
    subCategory: 'Média',
    language: 'en',
    active: true,
  },
  {
    id: 'stickyminds',
    name: 'StickyMinds',
    url: 'https://www.stickyminds.com/',
    feedUrl: 'https://www.stickyminds.com/rss.xml',
    category: CATEGORIES.QA,
    subCategory: 'Communauté',
    language: 'en',
    active: true,
  },
  {
    id: 'smartbear-blog',
    name: 'SmartBear Blog',
    url: 'https://smartbear.com/blog/',
    feedUrl: 'https://smartbear.com/blog/feed/',
    category: CATEGORIES.QA,
    subCategory: 'Éditeur',
    language: 'en',
    active: true,
  },
  {
    id: 'browserstack-blog',
    name: 'BrowserStack Blog',
    url: 'https://www.browserstack.com/blog',
    feedUrl: 'https://www.browserstack.com/blog/feed/',
    category: CATEGORIES.QA,
    subCategory: 'Éditeur',
    language: 'en',
    active: true,
  },
  {
    id: 'saucelabs-blog',
    name: 'Sauce Labs Blog',
    url: 'https://saucelabs.com/blog',
    feedUrl: 'https://saucelabs.com/blog/feed',
    category: CATEGORIES.QA,
    subCategory: 'Éditeur',
    language: 'en',
    active: true,
  },
  {
    id: 'lambdatest-blog',
    name: 'LambdaTest Blog',
    url: 'https://www.lambdatest.com/blog/',
    feedUrl: 'https://www.lambdatest.com/blog/feed/',
    category: CATEGORIES.QA,
    subCategory: 'Éditeur',
    language: 'en',
    active: true,
  },
  {
    id: 'software-testing-weekly',
    name: 'Software Testing Weekly',
    url: 'https://softwaretestingweekly.com/',
    feedUrl: 'https://softwaretestingweekly.com/feed.xml',
    category: CATEGORIES.QA,
    subCategory: 'Newsletter',
    language: 'en',
    active: true,
  },
  {
    id: 'cftl',
    name: 'CFTL',
    url: 'https://cftl.fr/',
    feedUrl: 'https://cftl.fr/feed/',
    category: CATEGORIES.QA,
    subCategory: 'Communauté FR',
    language: 'fr',
    active: true,
  },

  // ── IA & AUTOMATISATION ───────────────────────────────────────────────────
  {
    id: 'applitools-blog',
    name: 'Applitools Blog',
    url: 'https://applitools.com/blog/',
    feedUrl: 'https://applitools.com/blog/feed/',
    category: CATEGORIES.AI_TESTING,
    subCategory: 'Visual AI',
    language: 'en',
    active: true,
  },
  {
    id: 'mabl-blog',
    name: 'Mabl Blog',
    url: 'https://www.mabl.com/blog',
    feedUrl: 'https://www.mabl.com/blog/rss.xml',
    category: CATEGORIES.AI_TESTING,
    subCategory: 'Low-code testing',
    language: 'en',
    active: true,
  },
  {
    id: 'katalon-blog',
    name: 'Katalon Blog',
    url: 'https://katalon.com/resources-center/blog',
    feedUrl: 'https://katalon.com/blog/feed/',
    category: CATEGORIES.AI_TESTING,
    subCategory: 'Automation',
    language: 'en',
    active: true,
  },
  {
    id: 'functionize-blog',
    name: 'Functionize Blog',
    url: 'https://www.functionize.com/blog',
    feedUrl: 'https://www.functionize.com/blog/rss.xml',
    category: CATEGORIES.AI_TESTING,
    subCategory: 'AI Testing',
    language: 'en',
    active: true,
  },

  // ── PRIVACY & LÉGAL ───────────────────────────────────────────────────────
  {
    id: 'cnil-actualites',
    name: 'CNIL — Actualités',
    url: 'https://www.cnil.fr/fr/actualites',
    feedUrl: 'https://www.cnil.fr/fr/flux-rss-thematique-actualites',
    category: CATEGORIES.PRIVACY,
    subCategory: 'Régulateur FR',
    language: 'fr',
    active: true,
  },
  {
    id: 'edpb',
    name: 'EDPB — Actualités',
    url: 'https://www.edpb.europa.eu/news/news_en',
    feedUrl: 'https://www.edpb.europa.eu/news/news_en/feed_en',
    category: CATEGORIES.PRIVACY,
    subCategory: 'Régulateur EU',
    language: 'en',
    active: true,
  },
  {
    id: 'ico',
    name: 'ICO — News',
    url: 'https://ico.org.uk/about-the-ico/media-centre/news-and-blogs/',
    feedUrl: 'https://ico.org.uk/feed/',
    category: CATEGORIES.PRIVACY,
    subCategory: 'Régulateur UK',
    language: 'en',
    active: true,
  },
  {
    id: 'iapp-news',
    name: 'IAPP News',
    url: 'https://iapp.org/news/',
    feedUrl: 'https://iapp.org/news/feed/',
    category: CATEGORIES.PRIVACY,
    subCategory: 'Association',
    language: 'en',
    active: true,
  },
  {
    id: 'hogan-lovells-privacy',
    name: 'Hogan Lovells — Data Protection',
    url: 'https://www.hldataprotection.com/',
    feedUrl: 'https://www.hldataprotection.com/feed/',
    category: CATEGORIES.PRIVACY,
    subCategory: 'Cabinet juridique',
    language: 'en',
    active: true,
  },
  {
    id: 'hunton-privacy',
    name: 'Hunton Privacy Blog',
    url: 'https://www.huntonprivacyblog.com/',
    feedUrl: 'https://www.huntonprivacyblog.com/feed/',
    category: CATEGORIES.PRIVACY,
    subCategory: 'Cabinet juridique',
    language: 'en',
    active: true,
  },
  {
    id: 'global-privacy-blog',
    name: 'Latham — Global Privacy Blog',
    url: 'https://www.globalprivacyblog.com/',
    feedUrl: 'https://www.globalprivacyblog.com/feed/',
    category: CATEGORIES.PRIVACY,
    subCategory: 'Cabinet juridique',
    language: 'en',
    active: true,
  },
  {
    id: 'iab-europe',
    name: 'IAB Europe',
    url: 'https://iabeurope.eu/all-news/',
    feedUrl: 'https://iabeurope.eu/feed/',
    category: CATEGORIES.PRIVACY,
    subCategory: 'CMP / Ad Tech',
    language: 'en',
    active: true,
  },
  {
    id: 'didomi-blog',
    name: 'Didomi Blog',
    url: 'https://www.didomi.io/blog',
    feedUrl: 'https://www.didomi.io/blog/rss.xml',
    category: CATEGORIES.PRIVACY,
    subCategory: 'CMP / Ad Tech',
    language: 'fr',
    active: true,
  },
  {
    id: 'onetrust-blog',
    name: 'OneTrust Blog',
    url: 'https://www.onetrust.com/blog/',
    feedUrl: 'https://www.onetrust.com/blog/feed/',
    category: CATEGORIES.PRIVACY,
    subCategory: 'CMP / Ad Tech',
    language: 'en',
    active: true,
  },
  {
    id: 'techcrunch-privacy',
    name: 'TechCrunch — Privacy',
    url: 'https://techcrunch.com/category/privacy/',
    feedUrl: 'https://techcrunch.com/category/privacy/feed/',
    category: CATEGORIES.PRIVACY,
    subCategory: 'Média',
    language: 'en',
    active: true,
  },
  {
    id: 'the-record',
    name: 'The Record',
    url: 'https://therecord.media/',
    feedUrl: 'https://therecord.media/feed',
    category: CATEGORIES.PRIVACY,
    subCategory: 'Média',
    language: 'en',
    active: true,
  },
  {
    id: 'next-ink',
    name: 'Next INpact',
    url: 'https://next.ink/',
    feedUrl: 'https://next.ink/feed/',
    category: CATEGORIES.PRIVACY,
    subCategory: 'Média FR',
    language: 'fr',
    active: true,
  },
  {
    id: 'village-justice',
    name: 'Village de la Justice',
    url: 'https://www.village-justice.com/articles/',
    feedUrl: 'https://www.village-justice.com/articles/rss.php?type=article',
    category: CATEGORIES.PRIVACY,
    subCategory: 'Juridique FR',
    language: 'fr',
    active: true,
  },
];

// Helpers
function getSourceById(id) {
  return SOURCES.find(s => s.id === id) || null;
}

function getSourcesByCategory(category) {
  return SOURCES.filter(s => s.category === category && s.active);
}

function getAllCategories() {
  return Object.values(CATEGORIES);
}
